[project]
name = "githubctl"
version = "0.1.0"
description = "Add your description here"
authors = ["alfredoramirez3@outlook.com"]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "typer[all]>=0.15.1",
]
